spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/sales
    username: user
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 
          clientSecret: 
          scope:
           - email
           - profile
